GET http://localhost:5050

###  Signup/Register Route
POST http://localhost:5050/api/signup

### SignIn/Login Route
POST http://localhost:5050/api/signin

### Signout/logout
GET http://localhost:5050/api/signout



### UserInfo Route
GET http://localhost:5050/api/profile